version: '2.1'
services:
  mongo_host:
    image: 'docker.signzy.tech/mongo_go:4.2'
    container_name: "Mongo"
    restart: "always"
    stdin_open: true
    tty: true
    environment:
        - adminpass=signzyadmin
        - userpass=signzyuser
    security_opt:
      - no-new-privileges
    mem_limit: 10g
    cpu_shares: 2048
    healthcheck:
       test: ["CMD-SHELL","ps aux | grep mongod"]
       interval: 10s
       timeout: 5s
       retries: 5
    entrypoint: ["mongod","-f","/etc/mongod.conf","--replSet","sz","--keyFile","/etc/mongo-keyfile"]
    ports:
      - 51903:27017
    volumes:
      - ./data:/data/db
    extra_hosts:
        - "mongo1.prv:1.1.1.1"
        - "mongo2.prv:2.2.2.2"
        - "mongo3.prv:3.3.3.3"
