version: '2.2'

services:

  interview-localstack:
    image: localstack/localstack
    container_name: playment-localstack
    ports:
      - "4566-4597:4566-4597"
    environment:
      - DEFAULT_REGION=ap-southeast-1
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamo-db:
    image: amazon/dynamodb-local
    container_name: playment-dynamoDB
    ports:
      - 8000:8000

